version: "3.8"

services:
  app:
    environment:
      - SKIP_ENV_VALIDATION=true
      - DISABLE_PII_REDACTION=true
    env_file:
      - langwatch/.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      opensearch:
        condition: service_healthy

  langwatch_nlp:
    build:
      context: ./langwatch_nlp
    env_file:
      - langwatch/.env
    ports:
      - "8080:8080"
    restart: always
    environment:
      - LANGWATCH_ENDPOINT=http://app:3000

  langevals:
    image: langwatch/langevals:latest
    ports:
      - "8000:8000"
    restart: always
    pull_policy: always
    environment:
      - DISABLE_EVALUATORS_PRELOAD=true

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:2.17.1
    environment:
      - discovery.type=single-node
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xms512m -Djava.util.logging.config.file=logging.properties -Dlog4j2.formatMsgNoLookups=true"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=some-random-password-which-is-greater-than-16-chars-long
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1024m
          cpus: '1.0'
    restart: always

volumes:
  db-data:
  redis-data:
  opensearch-data:
