[project]
name = "langwatch_nlp"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dspy-ai == 2.5.10",
    "fastapi == 0.111.1",
    "google-cloud-aiplatform == 1.70.0",
    "httpx == 0.27.0",
    "langchain-community == 0.0.28",
    "langevals-core == 0.1.10",
    "langwatch>=0.1.31",
    "litellm[proxy] == 1.48.16",
    "mangum == 0.17.0",
    "nanoid == 2.0.0",
    "numpy == 1.26.4",
    "openai == 1.51.2",
    "pydantic == 2.9.2",
    "python-dotenv == 1.0.1",
    "scikit-learn == 1.5.2",
    "scipy == 1.14.1",
    "sentry-sdk[fastapi] == 1.45.1",
    "tenacity == 8.5.0",
    "uvicorn == 0.22.0",
    "weaviate-client == 4.8.1",
]

[project.optional-dependencies]
dev = [
    "pytest == 8.3.3",
    "pandas == 2.2.3",
    "pytest-httpx == 0.30.0",
    "pytest-asyncio == 0.23.8",
    "ipykernel == 6.29.5",
    "watchdog == 5.0.3",
]

[tool.uv]
package = false
