[tool.poetry]
name = "langwatch-nlp"
version = "0.1.0"
description = ""
authors = ["Rogerio Chaves <rogerio@langwatch.ai>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
fastapi = ">=0.109.1"
pydantic = "^2.9.2"
numpy = "^1.26.4"
openai = "^1.14.2"
sentry-sdk = { extras = ["fastapi"], version = "^1.42.0" }
scipy = "^1.12.0"
tenacity = "^8.2.3"
langchain-community = "^0.0.28"
nanoid = "^2.0.0"
python-dotenv = "^1.0.1"
mangum = "^0.17.0"
litellm = { extras = ["proxy"], version = "1.48.5" }
google-cloud-aiplatform = "^1.54.1"
uvicorn = ">=0.22.0,<0.23.0"
dspy-ai = "^2.5.2"
langevals-core = "^0.1.10"
httpx = "^0.27.2"
langwatch = { path = "../python-sdk", develop = true }
scikit-learn = "^1.5.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pandas = "^2.2.1"
pytest-httpx = "^0.30.0"
pytest-asyncio = "^0.23.7"
ipykernel = "^6.29.5"
watchdog = "^5.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
