name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push LangWatch NLP Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./langwatch_nlp
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: langwatch/langwatch_nlp:latest

      - name: Build and push LangWatch Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./langwatch
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: langwatch/langwatch:latest
